### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndryWJ** [ppiyush13/font-face-node#1]
`
import fontFaceNode from '@font-face/node' - not work

const fontFaceNode = require('@font-face/node'); - not work
`

`
"scripts": {
    "cr_fonts": "node ./node_scripts/cr_fonts.mjs" - not work
    "cr_fonts2": "node ./node_scripts/cr_fonts.js" - not work
  },
`

`set "type": "module"` - doesn't work too

Error:

`(node:14056) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Waiting for the debugger to disconnect...
F:\other\WebDev_v_2\Server\OSPanel\domains\corporatesite\node_modules\@font-face\node\src\execute.js:1
import fontfaceCore from '@font-face/core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)`

**Comment by ppiyush13** [comment]
@AndryWJ,

`@font-face/core` is not meant to be consumed programmatically. Instead it is a CLI tool to generate your font-face css file.

Steps: 
1. Install `npm install @font-face/node --save-dev`
2. Configure options via config file. Look https://github.com/ppiyush13/font-face-node#options for list of all options and  https://github.com/ppiyush13/font-face-node#cli-usage for all possible ways to define config file.
3. Execute `npx font-face` from bash

Upon execution you will find `font-face.css` getting generated.

So this answers your question ?

**Comment by AndryWJ** [comment]
I am trying to write a script that would take fonts from a folder and based on the name, collect the configuration and generate a css file.


```
fs.readdir(env.PATH_SRC+'fonts/FontsUse', (err, files) => {
    var fonts = [];
    files.forEach(file => {
        fonts.push(getFontsProperties(file));
    });

    console.log(fonts);
    // fontFaceNode({
    //     input: {
    //         dir: './src/fonts',
    //     },
    //     output: {
    //         dir: './dist',
    //         resourceDir: './dist/fontResources',
    //         cssFileName: 'font-face.css',
    //     },
    //     fonts: [
    //         {
    //             name: 'Roboto',
    //             weight: 200,
    //             style: 'normal',
    //             file: 'Roboto-Light',
    //         },
    //         {
    //             name: 'Roboto',
    //             weight: 400,
    //             style: 'normal',
    //             file: 'Roboto-Regular',
    //         },
    //         {
    //             name: 'Roboto',
    //             weight: 600,
    //             style: 'bold',
    //             file: 'Roboto-Medium',
    //         },
    //     ],
    // });

  });

  function getFontsProperties(fontFullName){
	  var out = {
		  'name' : fontFullName.match(/^(.*)-/)[1]
	  }
	  var weightConvert = {
	  'Thin' : 100,
	  'ExtraLight' : 200,
	  'Light' : 300,
	  'Regular' : 400,
	  'Medium' : 500,
	  'SemiBold' : 600,
	  'Bold' : 700,
	  'ExtraBold' : 800,
	  'Black' : 900
  };
	
	// .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
	var CamelCase = fontFullName.match(/.*-(.*)\./);
	var isItalic = CamelCase[1].match('Italic') !== null;
	if(isItalic){
		out['weight'] = weightConvert[CamelCase[1].replace('Italic','')];
		out['style'] = 'italic';
	}else{
		out['weight'] = weightConvert[CamelCase[1]];
		if(out['weight'] >= 600){ out['style'] = 'bold';}
		else{ out['style'] = 'normal'; }
	}
	
	return out;
}
```

It's a shame the module can't do this. But thanks for the answer.

**Comment by AndryWJ** [comment]
Although ... you can first save the configuration, and then read)) and run npx font-face. Thank you)

**Comment by ppiyush13** [comment]
You made a valid point. I have released version `@font-face/node@1.1.0`

Now you shall be able to execute below code:
```js
const fontFaceNode = require('@font-face/node');
fontFaceNode({
    input: {
        dir: './src/fonts',
    },
    output: {
        dir: './dist',
        resourceDir: './dist/fontResources',
        cssFileName: 'font-face.css',
    },
    fonts: [
        {
            name: 'Roboto',
            weight: 200,
            style: 'normal',
            file: 'Roboto-Light',
        },
        {
            name: 'Roboto',
            weight: 400,
            style: 'normal',
            file: 'Roboto-Regular',
        },
        {
            name: 'Roboto',
            weight: 600,
            style: 'bold',
            file: 'Roboto-Medium',
        },
    ],
});
```

Please upgrade and report if any issues.

**Comment by AndryWJ** [comment]
Many thanks! now I managed to do everything I wanted)
```

import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config();
const env = process.env;
import fontFaceNode from '@font-face/node';

fs.readdir(env.PATH_SRC+'fonts/FontsUse', (err, files) => {
    var fonts = [];
    files.forEach(file => {
        fonts.push(getFontsProperties(file));
    });

    fontFaceNode({
        input: {
            dir: env.PATH_SRC+'fonts/FontsUse',
        },
        output: {
            dir: env.PATH_DIST+'/fonts/dist/FontsUse',
            resourceDir: env.PATH_DIST+'/fonts/dist/FontsUse',
            cssFileName: 'fonts.css',
        },
        fonts: fonts,
    });

  });
  

  function getFontsProperties(fontFullName){
	var out = {
		'name' : fontFullName.match(/^(.*)-/)[1],
        'file' : fontFullName.match(/^(.*)\./)[1]
	}
	var weightConvert = {
        'Thin' : 100,
        'ExtraLight' : 200,
        'Light' : 300,
        'Regular' : 400,
        'Medium' : 500,
        'SemiBold' : 600,
        'Bold' : 700,
        'ExtraBold' : 800,
        'Black' : 900
    };

	var CamelCase = fontFullName.match(/.*-(.*)\./);
	var isItalic = CamelCase[1].match('Italic') !== null;
	if(isItalic){
		out['weight'] = weightConvert[CamelCase[1].replace('Italic','')];
		out['style'] = 'italic';
	}else{
		out['weight'] = weightConvert[CamelCase[1]];
		if(out['weight'] >= 600){ out['style'] = 'bold';}
		else{ out['style'] = 'normal'; }
	}
	return out;
}
```

**Comment by ppiyush13** [comment]
Thanks for reporting the issue.
